//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.ServicePosition {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.scania.com/fleet/contracts/positioning/v1", ConfigurationName="ServicePosition.PositioningInterface")]
    public interface PositioningInterface {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://xmlns.scania.com/fleet/schema/positioning/v1) of message GetFleetPositionRequest does not match the default value (http://xmlns.scania.com/fleet/contracts/positioning/v1)
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlns.scania.com/fleet/contracts/positioning/v1:getFleetPositionIn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MvcApplication1.ServicePosition.GetFleetPositionResponse GetFleetPosition(MvcApplication1.ServicePosition.GetFleetPositionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.276")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.scania.com/fleet/schema/positioning/v1")]
    public partial class FleetPosition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vinNumberField;
        
        private string chassisNumberField;
        
        private string registrationNumberField;
        
        private string vehicleAliasField;
        
        private string driverAliasField;
        
        private System.Nullable<int> odometerField;
        
        private System.Nullable<bool> ignitionField;
        
        private System.Nullable<System.DateTime> timeMessageField;
        
        private PositionType positionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string VinNumber {
            get {
                return this.vinNumberField;
            }
            set {
                this.vinNumberField = value;
                this.RaisePropertyChanged("VinNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string ChassisNumber {
            get {
                return this.chassisNumberField;
            }
            set {
                this.chassisNumberField = value;
                this.RaisePropertyChanged("ChassisNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string RegistrationNumber {
            get {
                return this.registrationNumberField;
            }
            set {
                this.registrationNumberField = value;
                this.RaisePropertyChanged("RegistrationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string VehicleAlias {
            get {
                return this.vehicleAliasField;
            }
            set {
                this.vehicleAliasField = value;
                this.RaisePropertyChanged("VehicleAlias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string DriverAlias {
            get {
                return this.driverAliasField;
            }
            set {
                this.driverAliasField = value;
                this.RaisePropertyChanged("DriverAlias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<int> Odometer {
            get {
                return this.odometerField;
            }
            set {
                this.odometerField = value;
                this.RaisePropertyChanged("Odometer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public System.Nullable<bool> Ignition {
            get {
                return this.ignitionField;
            }
            set {
                this.ignitionField = value;
                this.RaisePropertyChanged("Ignition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> TimeMessage {
            get {
                return this.timeMessageField;
            }
            set {
                this.timeMessageField = value;
                this.RaisePropertyChanged("TimeMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public PositionType position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.276")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.scania.com/fleet/schema/positioning/v1")]
    public partial class PositionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<double> latitudeField;
        
        private System.Nullable<double> longitudeField;
        
        private System.Nullable<int> speedField;
        
        private System.Nullable<int> headingField;
        
        private System.Nullable<System.DateTime> timePositionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<double> Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<double> Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int> Speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
                this.RaisePropertyChanged("Speed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<int> Heading {
            get {
                return this.headingField;
            }
            set {
                this.headingField = value;
                this.RaisePropertyChanged("Heading");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> TimePosition {
            get {
                return this.timePositionField;
            }
            set {
                this.timePositionField = value;
                this.RaisePropertyChanged("TimePosition");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FleetPositionRequest", WrapperNamespace="http://xmlns.scania.com/fleet/schema/positioning/v1", IsWrapped=true)]
    public partial class GetFleetPositionRequest {
        
        public GetFleetPositionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FleetPositionResponse", WrapperNamespace="http://xmlns.scania.com/fleet/schema/positioning/v1", IsWrapped=true)]
    public partial class GetFleetPositionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.scania.com/fleet/schema/positioning/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("FleetPosition", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FleetPosition[] FleetPosition;
        
        public GetFleetPositionResponse() {
        }
        
        public GetFleetPositionResponse(FleetPosition[] FleetPosition) {
            this.FleetPosition = FleetPosition;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PositioningInterfaceChannel : MvcApplication1.ServicePosition.PositioningInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PositioningInterfaceClient : System.ServiceModel.ClientBase<MvcApplication1.ServicePosition.PositioningInterface>, MvcApplication1.ServicePosition.PositioningInterface {
        
        public PositioningInterfaceClient() {
        }
        
        public PositioningInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PositioningInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PositioningInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PositioningInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcApplication1.ServicePosition.GetFleetPositionResponse MvcApplication1.ServicePosition.PositioningInterface.GetFleetPosition(MvcApplication1.ServicePosition.GetFleetPositionRequest request) {
            return base.Channel.GetFleetPosition(request);
        }
        
        public FleetPosition[] GetFleetPosition() {
            MvcApplication1.ServicePosition.GetFleetPositionRequest inValue = new MvcApplication1.ServicePosition.GetFleetPositionRequest();
            MvcApplication1.ServicePosition.GetFleetPositionResponse retVal = ((MvcApplication1.ServicePosition.PositioningInterface)(this)).GetFleetPosition(inValue);
            return retVal.FleetPosition;
        }
    }
}
