//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.ServiceVehicule {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.scania.com/fleet/contract/vehicleanalysis/v1", ConfigurationName="ServiceVehicule.VehicleAnalysisInterface")]
    public interface VehicleAnalysisInterface {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://xmlns.scania.com/fleet/schema/vehicleanalysis/v1) of message GetVehicleAnalysisRequest does not match the default value (http://xmlns.scania.com/fleet/contract/vehicleanalysis/v1)
        [System.ServiceModel.OperationContractAttribute(Action="http://xmlns.scania.com/fleet/contract/vehicleanalysis/v1:getVehicleAnalysisIn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MvcApplication1.ServiceVehicule.GetVehicleAnalysisResponse GetVehicleAnalysis(MvcApplication1.ServiceVehicule.GetVehicleAnalysisRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.276")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.scania.com/fleet/schema/vehicleanalysis/v1")]
    public partial class VehicleAnalysisType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BasicInformationType basicInformationField;
        
        private FuelConsumptionType fuelConsumptionField;
        
        private DriverBehaviourType driverBehaviourField;
        
        private MaintenanceType maintenanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public BasicInformationType BasicInformation {
            get {
                return this.basicInformationField;
            }
            set {
                this.basicInformationField = value;
                this.RaisePropertyChanged("BasicInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public FuelConsumptionType FuelConsumption {
            get {
                return this.fuelConsumptionField;
            }
            set {
                this.fuelConsumptionField = value;
                this.RaisePropertyChanged("FuelConsumption");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DriverBehaviourType DriverBehaviour {
            get {
                return this.driverBehaviourField;
            }
            set {
                this.driverBehaviourField = value;
                this.RaisePropertyChanged("DriverBehaviour");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public MaintenanceType Maintenance {
            get {
                return this.maintenanceField;
            }
            set {
                this.maintenanceField = value;
                this.RaisePropertyChanged("Maintenance");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.276")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.scania.com/fleet/schema/vehicleanalysis/v1")]
    public partial class BasicInformationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vinNumberField;
        
        private string chassisNumberField;
        
        private string registrationNumberField;
        
        private string vehicleAliasField;
        
        private string driverAliasField;
        
        private System.Nullable<int> odometerField;
        
        private System.Nullable<bool> ignitionField;
        
        private System.Nullable<System.DateTime> timeMessageField;
        
        private System.Nullable<int> fuelLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string VinNumber {
            get {
                return this.vinNumberField;
            }
            set {
                this.vinNumberField = value;
                this.RaisePropertyChanged("VinNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string ChassisNumber {
            get {
                return this.chassisNumberField;
            }
            set {
                this.chassisNumberField = value;
                this.RaisePropertyChanged("ChassisNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string RegistrationNumber {
            get {
                return this.registrationNumberField;
            }
            set {
                this.registrationNumberField = value;
                this.RaisePropertyChanged("RegistrationNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string VehicleAlias {
            get {
                return this.vehicleAliasField;
            }
            set {
                this.vehicleAliasField = value;
                this.RaisePropertyChanged("VehicleAlias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string DriverAlias {
            get {
                return this.driverAliasField;
            }
            set {
                this.driverAliasField = value;
                this.RaisePropertyChanged("DriverAlias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<int> Odometer {
            get {
                return this.odometerField;
            }
            set {
                this.odometerField = value;
                this.RaisePropertyChanged("Odometer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public System.Nullable<bool> Ignition {
            get {
                return this.ignitionField;
            }
            set {
                this.ignitionField = value;
                this.RaisePropertyChanged("Ignition");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> TimeMessage {
            get {
                return this.timeMessageField;
            }
            set {
                this.timeMessageField = value;
                this.RaisePropertyChanged("TimeMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public System.Nullable<int> FuelLevel {
            get {
                return this.fuelLevelField;
            }
            set {
                this.fuelLevelField = value;
                this.RaisePropertyChanged("FuelLevel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.276")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.scania.com/fleet/schema/vehicleanalysis/v1")]
    public partial class MaintenanceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> serviceIntervalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> ServiceInterval {
            get {
                return this.serviceIntervalField;
            }
            set {
                this.serviceIntervalField = value;
                this.RaisePropertyChanged("ServiceInterval");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.276")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.scania.com/fleet/schema/vehicleanalysis/v1")]
    public partial class DriverBehaviourType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> totalNoOfBrakeApplicationsField;
        
        private System.Nullable<int> totalDistanceWithTrailerField;
        
        private System.Nullable<int> totalNoOfHarshAccelerationField;
        
        private System.Nullable<int> totalNoOfHarshBrakesField;
        
        private System.Nullable<int> totalTimeOverrevingField;
        
        private System.Nullable<int> totalTimeOverspeedingField;
        
        private System.Nullable<int> distanceMovingWhileOutOfGearField;
        
        private System.Nullable<int> distanceWithCCActiveField;
        
        private System.Nullable<int> maxRPMBrakingField;
        
        private System.Nullable<int> maxRPMDrivingField;
        
        private System.Nullable<int> maxSpeedField;
        
        private System.Nullable<int> timeOutOfGreenBandDrivingField;
        
        private System.Nullable<int> coastingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> TotalNoOfBrakeApplications {
            get {
                return this.totalNoOfBrakeApplicationsField;
            }
            set {
                this.totalNoOfBrakeApplicationsField = value;
                this.RaisePropertyChanged("TotalNoOfBrakeApplications");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<int> TotalDistanceWithTrailer {
            get {
                return this.totalDistanceWithTrailerField;
            }
            set {
                this.totalDistanceWithTrailerField = value;
                this.RaisePropertyChanged("TotalDistanceWithTrailer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int> TotalNoOfHarshAcceleration {
            get {
                return this.totalNoOfHarshAccelerationField;
            }
            set {
                this.totalNoOfHarshAccelerationField = value;
                this.RaisePropertyChanged("TotalNoOfHarshAcceleration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<int> TotalNoOfHarshBrakes {
            get {
                return this.totalNoOfHarshBrakesField;
            }
            set {
                this.totalNoOfHarshBrakesField = value;
                this.RaisePropertyChanged("TotalNoOfHarshBrakes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public System.Nullable<int> TotalTimeOverreving {
            get {
                return this.totalTimeOverrevingField;
            }
            set {
                this.totalTimeOverrevingField = value;
                this.RaisePropertyChanged("TotalTimeOverreving");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<int> TotalTimeOverspeeding {
            get {
                return this.totalTimeOverspeedingField;
            }
            set {
                this.totalTimeOverspeedingField = value;
                this.RaisePropertyChanged("TotalTimeOverspeeding");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public System.Nullable<int> DistanceMovingWhileOutOfGear {
            get {
                return this.distanceMovingWhileOutOfGearField;
            }
            set {
                this.distanceMovingWhileOutOfGearField = value;
                this.RaisePropertyChanged("DistanceMovingWhileOutOfGear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public System.Nullable<int> DistanceWithCCActive {
            get {
                return this.distanceWithCCActiveField;
            }
            set {
                this.distanceWithCCActiveField = value;
                this.RaisePropertyChanged("DistanceWithCCActive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public System.Nullable<int> MaxRPMBraking {
            get {
                return this.maxRPMBrakingField;
            }
            set {
                this.maxRPMBrakingField = value;
                this.RaisePropertyChanged("MaxRPMBraking");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public System.Nullable<int> MaxRPMDriving {
            get {
                return this.maxRPMDrivingField;
            }
            set {
                this.maxRPMDrivingField = value;
                this.RaisePropertyChanged("MaxRPMDriving");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public System.Nullable<int> MaxSpeed {
            get {
                return this.maxSpeedField;
            }
            set {
                this.maxSpeedField = value;
                this.RaisePropertyChanged("MaxSpeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public System.Nullable<int> TimeOutOfGreenBandDriving {
            get {
                return this.timeOutOfGreenBandDrivingField;
            }
            set {
                this.timeOutOfGreenBandDrivingField = value;
                this.RaisePropertyChanged("TimeOutOfGreenBandDriving");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public System.Nullable<int> Coasting {
            get {
                return this.coastingField;
            }
            set {
                this.coastingField = value;
                this.RaisePropertyChanged("Coasting");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.276")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.scania.com/fleet/schema/vehicleanalysis/v1")]
    public partial class FuelConsumptionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> totalFuelField;
        
        private System.Nullable<int> totalFuelIdleField;
        
        private System.Nullable<int> totalRuntimeField;
        
        private System.Nullable<int> totalRuntimeIdleField;
        
        private System.Nullable<int> totalFuelPTOField;
        
        private System.Nullable<int> totalRuntimePTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> TotalFuel {
            get {
                return this.totalFuelField;
            }
            set {
                this.totalFuelField = value;
                this.RaisePropertyChanged("TotalFuel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<int> TotalFuelIdle {
            get {
                return this.totalFuelIdleField;
            }
            set {
                this.totalFuelIdleField = value;
                this.RaisePropertyChanged("TotalFuelIdle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int> TotalRuntime {
            get {
                return this.totalRuntimeField;
            }
            set {
                this.totalRuntimeField = value;
                this.RaisePropertyChanged("TotalRuntime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<int> TotalRuntimeIdle {
            get {
                return this.totalRuntimeIdleField;
            }
            set {
                this.totalRuntimeIdleField = value;
                this.RaisePropertyChanged("TotalRuntimeIdle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public System.Nullable<int> TotalFuelPTO {
            get {
                return this.totalFuelPTOField;
            }
            set {
                this.totalFuelPTOField = value;
                this.RaisePropertyChanged("TotalFuelPTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public System.Nullable<int> TotalRuntimePTO {
            get {
                return this.totalRuntimePTOField;
            }
            set {
                this.totalRuntimePTOField = value;
                this.RaisePropertyChanged("TotalRuntimePTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VehicleAnalysisRequest", WrapperNamespace="http://xmlns.scania.com/fleet/schema/vehicleanalysis/v1", IsWrapped=true)]
    public partial class GetVehicleAnalysisRequest {
        
        public GetVehicleAnalysisRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VehicleAnalysisResponse", WrapperNamespace="http://xmlns.scania.com/fleet/schema/vehicleanalysis/v1", IsWrapped=true)]
    public partial class GetVehicleAnalysisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.scania.com/fleet/schema/vehicleanalysis/v1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("VehicleAnalysis", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VehicleAnalysisType[] VehicleAnalysis;
        
        public GetVehicleAnalysisResponse() {
        }
        
        public GetVehicleAnalysisResponse(VehicleAnalysisType[] VehicleAnalysis) {
            this.VehicleAnalysis = VehicleAnalysis;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VehicleAnalysisInterfaceChannel : MvcApplication1.ServiceVehicule.VehicleAnalysisInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehicleAnalysisInterfaceClient : System.ServiceModel.ClientBase<MvcApplication1.ServiceVehicule.VehicleAnalysisInterface>, MvcApplication1.ServiceVehicule.VehicleAnalysisInterface {
        
        public VehicleAnalysisInterfaceClient() {
        }
        
        public VehicleAnalysisInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehicleAnalysisInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleAnalysisInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleAnalysisInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcApplication1.ServiceVehicule.GetVehicleAnalysisResponse MvcApplication1.ServiceVehicule.VehicleAnalysisInterface.GetVehicleAnalysis(MvcApplication1.ServiceVehicule.GetVehicleAnalysisRequest request) {
            return base.Channel.GetVehicleAnalysis(request);
        }
        
        public VehicleAnalysisType[] GetVehicleAnalysis() {
            MvcApplication1.ServiceVehicule.GetVehicleAnalysisRequest inValue = new MvcApplication1.ServiceVehicule.GetVehicleAnalysisRequest();
            MvcApplication1.ServiceVehicule.GetVehicleAnalysisResponse retVal = ((MvcApplication1.ServiceVehicule.VehicleAnalysisInterface)(this)).GetVehicleAnalysis(inValue);
            return retVal.VehicleAnalysis;
        }
    }
}
